### ISSUE TITLE
Uncaught ReferenceError: DEBUG is not defined | Stage.js 0.9.4 + Vue.js v3.3.4

### ISSUE THREAD

**Issue by LuckyFox31** [piqnt/stage.js#63]
> Stage.js version : `0.9.4`
> Vue.js version `3.3.4`
> Development environment : `Vite`
> Package manager : `PNPM 8.6.9`

I created a small project with the Vue.js framework to test the Stage.js library.

When I try to import the library I get an error: 
```
Uncaught ReferenceError: DEBUG is not defined
    at node_modules/.pnpm/stage-js@0.9.4/node_modules/stage-js/lib/core.js (core.js:2:3)
    at __require (chunk-76J2PTFD.js?v=a126181c:3:50)
    at node_modules/.pnpm/stage-js@0.9.4/node_modules/stage-js/lib/index.js (index.js:1:18)
    at __require (chunk-76J2PTFD.js?v=a126181c:3:50)
    at node_modules/.pnpm/stage-js@0.9.4/node_modules/stage-js/platform/web.js (web.js:1:18)
    at __require (chunk-76J2PTFD.js?v=a126181c:3:50)
    at web.js:16:1
```

This error appears in this import: 
```js
import {Stage} from "stage-js/platform/web.js"
```
I also tried this import: 
```js
import {Stage} from "stage-js/platform/web.js"
```

Here is my code : 
```vue
<script setup>
  // -- Dependencies --
  import {ref, onMounted} from "vue";
  import {Stage} from "stage-js/platform/web.js" // <-- Here

  // -- References --
  const gameContainer = ref(null);

  // -- Variables --
  let stage;

  // -- Life cycles --
  onMounted(() => {
    stage = new Stage(gameContainer.value);
  })
</script>

<template>
  <div ref="gameContainer"></div>
</template>

<style scoped>
  div{
    width: 1000px;
    height: 1000px;
  }
</style>
```

Has anyone ever encountered this error?
How can I solve this problem?

**Comment by shakiba** [comment]
Hi @LuckyFox31 , please temporary add `var DEBUG = false;` or true to your code, I'm working on a new major update, but will make an minor update to just a fix this issue today.

**Comment by shakiba** [comment]
I published 0.9.5, could you please try again?

**Comment by LuckyFox31** [comment]
It works, thank you.

But now I have to use this syntax to import the library: 
```js
import * as Stage from "stage-js" // Work

import {Stage} from "stage-js/platform/web.js" // Not working
import {Stage} from "stage-js"// Not working
```

I can't wait to see the new version! ;)

Thanks for the fix!
